export const jwtConstants = {
  // TODO - MOVE THIS TO AN ENVIRONMENT VARIABLE
  secret:
    'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
};
